# Site settings
title: mlr.press
email: 
description: > # this means to ignore newlines until "baseurl:"
mlr.press is the new home for the proceedings of machine learning reserach (pmlr)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mlr.press" # the base hostname & protocol for your site
twitter_username: 
github_username:  mlresearch

# Build settings
markdown: kramdown
