# Site settings
title: Proceedings of Machine Learning Resesrch
email: 
description: > # this means to ignore newlines until "baseurl:"
  mlr.press is the new home for the proceedings of machine learning reserach (pmlr)
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://proceedings.mlr.press" # the base hostname & protocol for your site
twitter_username: 
github_username:  mlresearch

repository: mlresearch/mlresearch.github.io
# Build settings
markdown: kramdown
